### ISSUE TITLE
When app is first opened, automatically `Select files` 

### ISSUE THREAD

**Issue by reynoldsnlp** [BYU-ODH/electron_player#10]
Don't make the user click `Select files`.

**Comment by konnorjp** [comment]
Javascript gives the following warning with trying to automatically "click" on the file picker input element: File chooser dialog can only be shown with a user activation. 

I think a work around is possible, but I don't think it's worth it.

**Comment by reynoldsnlp** [comment]
@konnorjp I agree. It's not worth it.
