### ISSUE TITLE
Select files button is only visible if the window is large enough.

### ISSUE THREAD

**Issue by reynoldsnlp** [BYU-ODH/electron_player#11]
Make it responsive, with the button in the middle of the screen. Maybe make the ic symbol much smaller, to the side or in the corner.

**Comment by konnorjp** [comment]
With commit 94c8796 I made the select files button responsive relative to the bottom of the screen, it is always visible in the center of the screen horizontally and moves on top of the ic symbol, which is now static in the center top of the screen.
