### ISSUE TITLE
Upgrade to latest electron version

### ISSUE THREAD

**Issue by reynoldsnlp** [BYU-ODH/electron_player#13]
This is a great summer project.

**Comment by konnorjp** [comment]
It's possible that with commit 95a68bc this was achieved to a certain extent. I'm not sure what exactly it involves.

**Comment by reynoldsnlp** [comment]
@verdude do you remember why I made this issue? Was it after the patch that you made?

**Comment by verdude** [comment]
Yea, IIRC there used to be a package.json file that was not using the most up to date electron version. For some reason, there doesn't seem to be a package.json anywhere anymore.
However, I don't remember what issue that version of electron had.
