### ISSUE TITLE
interpolate censor movement on json load if 'interpolate' flag is true

### ISSUE THREAD

**Issue by reynoldsnlp** [BYU-ODH/electron_player#16]
If a censor in the json has an `interpolate` flag set to `true`, then when the json object is loaded into `player.annotations`, interpolate positions every 1/30th of a second (or is some other interval more appropriate?).

```json
[
  {
    "options": {
	  "label": "Words 48:37",
      "start": "2917",
      "end": "2922",
      "type": "censor",
      "details": {
        "type": "blur",
        "amount": "30px",
        "interpolate": true,
        "position": {
          "2917":     [55, 79, 4, 5],
          "2927":     [65, 20, 4, 5],
        }
      }
    }
  }
]
```

**Comment by reynoldsnlp** [comment]
See https://github.com/BYU-ODH/electron_player/blob/master/scripts/interpolate.py for example logic to do the interpolation.

**Comment by konnorjp** [comment]
Censors interpolate with commit b894738
Interpolations are seen with commit db6fcc4
I added an intPositions dict to the details of the annotation. It also needs to be updated on draggable and resizeable. It will appear super choppy after a drag or resize when watching the video with interpolation until the interpolations are recreated.
