### ISSUE TITLE
Validate json when it is loaded

### ISSUE THREAD

**Issue by reynoldsnlp** [BYU-ODH/electron_player#8]
Make sure that the censor annotations have sane start and end times, and that annotations are in the right order.

If there are problems with start and end times, then warn the user with a helpful, informative `alert` message. Use the annotation `label` value, if it exists, otherwise just use times to refer to an annotation.

If there is a problem with the order of the annotations, recover by automatically reordering the annotations, and warn the user with an `alert` message that tells which annotations were out of place. Use the annotation `label` value, if it exists, otherwise just use times to refer to an annotation.

**Comment by reynoldsnlp** [comment]
If the first start time in the `position` dictionary doesn't match the annotation's `start` time, then warn the user with an alert with the `label`, but then gracefully correct the first `position` to match the `start` time.

**Comment by konnorjp** [comment]
What is the correct order for annotations? 

I currently don't see a `label` value. What is it supposed to look like?

**Comment by reynoldsnlp** [comment]
@konnorjp this is the template that I use for IC. The `label` is just a human-readable string for convenience. I usually use it to describe what is being skipped/blurred and to give a human-readable time (MM:SS instead of just seconds).

```json
[
  {"options": {"label": "0:25:10 - 0:25:16", "type": "skip", "start": "1509.5", "end": "1509.6", "details": {}}},

  {
    "options": {
          "label": "Words 48:37",
      "start": "2917",
      "end": "2922",
      "type": "censor",
      "details": {
        "type": "blur",
        "amount": "30px",
        "position": {
          "2917":     [55, 79, 4, 5]
        }
      }
    }
  }
]
```

**Comment by konnorjp** [comment]
In the code, we check for 
`case 'mute':
case 'mutePlugin':`

I assume that `mutePlugin` is just another form of `mute` but I think that we can remove `mutePlugin` from the code.

Also, I'm not sure what this part of the `"details"` does for the censor annotation. We never access the value `'size'`.
``` json
"size": {
  "6": "10"
}
```
``` json
{
    "options": {
      "start": "6",
      "end": "19",
      "type": "censor",
      "details": {
        "type": "blur",
        "interpolate": true,
        "amount": "30px",
        "size": {
          "6": "10"
        },
        "position": { }
    }
  }
}
```

**Comment by reynoldsnlp** [comment]
The `mutePlugin` is a holdover to be compatible with `hummedia.byu.edu`. Let's leave it for now.

The `size` attribute is vestigial from before we started doing the `position` mapping with `x`/`y`/`w`/`h`, so it is obsolete. We can just get rid of it altogether.

**Comment by konnorjp** [comment]
I adjusted the correction for the first position and the start time.

> If the first start time in the `position` dictionary doesn't match the annotation's `start` time, then warn the user with an alert with the `label`, but then gracefully correct the first `position` to match the `start` time.

Instead, when the first time in the `position` is larger than the `start` time, the first `position` becomes the `start` time as planned. But if the first time in the `position` is smaller than the `start` time, the `start` time becomes the first `position` time, since we might have to check each time after the first `position` time to determine how it relates to the `start` time.
